# Generated by Django 4.0.3 on 2022-10-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0013_remove_everside_nps_client_naics'),
    ]

    operations = [
        migrations.AddField(
            model_name='everside_nps',
            name='CLINIC_STATE_FULL',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
